CREATE TABLE [PacotesHistorico] (
    [Id] int NOT NULL IDENTITY,
    [PacoteId] int NOT NULL,
    [TITULO] nvarchar(max) NOT NULL,
    [DESCRICAO] nvarchar(max) NOT NULL,
    [DESTINO] nvarchar(max) NOT NULL,
    [ESTRELAS] int NOT NULL,
    [DURACAO] int NOT NULL,
    [DATA_DISPONIVEL] datetime2 NOT NULL,
    [VALOR_TOTAL] real NOT NULL,
    [QUANTIDADE_MAXIMA] int NOT NULL,
    [CRIADO_POR] nvarchar(max) NULL,
    [CRIADO_EM] datetime2 NULL,
    [ATUALIZADO_POR] nvarchar(max) NULL,
    [ATUALIZADO_EM] datetime2 NULL,
    [VERSÃO] int NOT NULL,
    [CATEGORIAS] nvarchar(max) NOT NULL,
    CONSTRAINT [PK_PacotesHistorico] PRIMARY KEY ([Id])
);
GO


CREATE TABLE [TB_PROMOCOES] (
    [Id] int NOT NULL IDENTITY,
    [NOME] nvarchar(max) NOT NULL,
    [DESCRICAO] nvarchar(max) NOT NULL,
    [DESCONTO_PERCENTUAL] real NOT NULL,
    [DATA_INICIO] datetime2 NOT NULL,
    [DATA_FIM] datetime2 NOT NULL,
    CONSTRAINT [PK_TB_PROMOCOES] PRIMARY KEY ([Id])
);
GO


CREATE TABLE [TB_TIPO_USUARIO] (
    [Id] int NOT NULL IDENTITY,
    [NOME] nvarchar(max) NOT NULL,
    CONSTRAINT [PK_TB_TIPO_USUARIO] PRIMARY KEY ([Id])
);
GO


CREATE TABLE [TB_PACOTES] (
    [Id] int NOT NULL IDENTITY,
    [TITULO] nvarchar(max) NOT NULL,
    [DESCRICAO] nvarchar(max) NOT NULL,
    [DESTINO] nvarchar(max) NOT NULL,
    [ESTRELAS] int NOT NULL,
    [DURACAO] int NOT NULL,
    [DATA_DISPONIVEL] datetime2 NOT NULL,
    [VALOR_TOTAL] real NOT NULL,
    [QUANTIDADE_MAXIMA] int NOT NULL,
    [CRIADO_POR] nvarchar(max) NULL,
    [CRIADO_EM] datetime2 NULL,
    [ATUALIZADO_POR] nvarchar(max) NULL,
    [ATUALIZADO_EM] datetime2 NULL,
    [VERSÃO] int NOT NULL,
    [CATEGORIAS] nvarchar(max) NOT NULL,
    [PromocaoId] int NULL,
    CONSTRAINT [PK_TB_PACOTES] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_PACOTES_TB_PROMOCOES_PromocaoId] FOREIGN KEY ([PromocaoId]) REFERENCES [TB_PROMOCOES] ([Id])
);
GO


CREATE TABLE [TB_USUARIOS] (
    [Id] int NOT NULL IDENTITY,
    [NOME] nvarchar(max) NOT NULL,
    [CPF] nvarchar(max) NOT NULL,
    [TELEFONE] nvarchar(max) NOT NULL,
    [DATA_NASCIMENTO] datetime2 NOT NULL,
    [EMAIL] nvarchar(max) NOT NULL,
    [EMAIL_COMFIRMADO] bit NOT NULL,
    [TOKEN_EMAILCONFIRMADO] nvarchar(max) NULL,
    [TOKEN_EXPIRACAO_EMAILCONFIRMADO] datetime2 NULL,
    [TOKEN_RECUPERACAO_SENHA] nvarchar(max) NULL,
    [TOKEN_EXPIRACAO_RECUPERACAO_SENHA] datetime2 NULL,
    [SENHA] nvarchar(max) NOT NULL,
    [TIPO_USUARIO_ID] int NOT NULL,
    CONSTRAINT [PK_TB_USUARIOS] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_USUARIOS_TB_TIPO_USUARIO_TIPO_USUARIO_ID] FOREIGN KEY ([TIPO_USUARIO_ID]) REFERENCES [TB_TIPO_USUARIO] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [ImagensPacote] (
    [Id] int NOT NULL IDENTITY,
    [Url] nvarchar(max) NOT NULL,
    [PacoteId] int NOT NULL,
    [HistoricoPacoteId] int NULL,
    CONSTRAINT [PK_ImagensPacote] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_ImagensPacote_PacotesHistorico_HistoricoPacoteId] FOREIGN KEY ([HistoricoPacoteId]) REFERENCES [PacotesHistorico] ([Id]),
    CONSTRAINT [FK_ImagensPacote_TB_PACOTES_PacoteId] FOREIGN KEY ([PacoteId]) REFERENCES [TB_PACOTES] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_MIDIAS] (
    [Id] int NOT NULL IDENTITY,
    [TIPO] nvarchar(max) NOT NULL,
    [URL] nvarchar(max) NOT NULL,
    [PACOTE_ID] int NOT NULL,
    [PACOTE_ID1] int NOT NULL,
    CONSTRAINT [PK_TB_MIDIAS] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_MIDIAS_TB_PACOTES_PACOTE_ID1] FOREIGN KEY ([PACOTE_ID1]) REFERENCES [TB_PACOTES] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [VideosPacote] (
    [Id] int NOT NULL IDENTITY,
    [Url] nvarchar(max) NOT NULL,
    [PacoteId] int NOT NULL,
    [HistoricoPacoteId] int NULL,
    CONSTRAINT [PK_VideosPacote] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_VideosPacote_PacotesHistorico_HistoricoPacoteId] FOREIGN KEY ([HistoricoPacoteId]) REFERENCES [PacotesHistorico] ([Id]),
    CONSTRAINT [FK_VideosPacote_TB_PACOTES_PacoteId] FOREIGN KEY ([PacoteId]) REFERENCES [TB_PACOTES] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_CARTOES] (
    [Id] int NOT NULL IDENTITY,
    [USUARIO_ID] int NOT NULL,
    [NOME_TITULAR] nvarchar(max) NOT NULL,
    [NUMERO_CARTAO] nvarchar(max) NOT NULL,
    [VALIDADE] nvarchar(max) NOT NULL,
    [CVV] nvarchar(max) NOT NULL,
    [TIPO_CARTAO] nvarchar(max) NOT NULL,
    [APELIDO] nvarchar(max) NULL,
    [ATIVO] bit NOT NULL,
    CONSTRAINT [PK_TB_CARTOES] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_CARTOES_TB_USUARIOS_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [TB_USUARIOS] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_DOCUMENTOS] (
    [Id] int NOT NULL IDENTITY,
    [TIPO_DOCUMENTO] nvarchar(max) NOT NULL,
    [NUMERO_DOCUMENTO] nvarchar(max) NOT NULL,
    [USUARIO_ID] int NOT NULL,
    CONSTRAINT [PK_TB_DOCUMENTOS] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_DOCUMENTOS_TB_USUARIOS_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [TB_USUARIOS] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_ENDERECOS] (
    [Id] int NOT NULL IDENTITY,
    [USUARIO_ID] int NOT NULL,
    [CEP] nvarchar(max) NOT NULL,
    [LOGRADOURO] nvarchar(max) NOT NULL,
    [NUMERO] nvarchar(max) NOT NULL,
    [COMPLEMENTO] nvarchar(max) NULL,
    [BAIRRO] nvarchar(max) NOT NULL,
    [CIDADE] nvarchar(max) NOT NULL,
    [ESTADO] nvarchar(max) NOT NULL,
    [PAIS] nvarchar(max) NOT NULL,
    [APELIDO] nvarchar(max) NULL,
    [ATIVO] bit NOT NULL,
    CONSTRAINT [PK_TB_ENDERECOS] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_ENDERECOS_TB_USUARIOS_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [TB_USUARIOS] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_RESERVAS] (
    [Id] int NOT NULL IDENTITY,
    [NUMERO_RESERVA] int NOT NULL,
    [DATA_RESERVA] datetime2 NOT NULL,
    [DATA_VIAGEM] datetime2 NULL,
    [STATUS] nvarchar(max) NOT NULL,
    [VALOR_UNITARIO] real NOT NULL,
    [QUANTIDADE_VIAJANTES] int NULL,
    [VALOR_TOTAL] decimal(18,2) NULL,
    [USUARIO_ID] int NOT NULL,
    [PACOTE_ID] int NOT NULL,
    CONSTRAINT [PK_TB_RESERVAS] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_RESERVAS_TB_PACOTES_PACOTE_ID] FOREIGN KEY ([PACOTE_ID]) REFERENCES [TB_PACOTES] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_RESERVAS_TB_USUARIOS_USUARIO_ID] FOREIGN KEY ([USUARIO_ID]) REFERENCES [TB_USUARIOS] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_AVALIACOES] (
    [Id] int NOT NULL IDENTITY,
    [STATUS] nvarchar(max) NOT NULL,
    [NOTA] int NOT NULL,
    [COMENTARIO] nvarchar(max) NOT NULL,
    [DATA_AVALIACAO] datetime2 NOT NULL,
    [ID_RESERVA] int NOT NULL,
    CONSTRAINT [PK_TB_AVALIACOES] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_AVALIACOES_TB_RESERVAS_ID_RESERVA] FOREIGN KEY ([ID_RESERVA]) REFERENCES [TB_RESERVAS] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_PAGAMENTOS] (
    [Id] int NOT NULL IDENTITY,
    [VALOR] real NOT NULL,
    [FORMA_DE_PAGAMENTO] nvarchar(max) NOT NULL,
    [DATA_PAGAMENTO] datetime2 NOT NULL,
    [STATUS_PAGAMENTO] nvarchar(max) NOT NULL,
    [ID_RESERVA] int NOT NULL,
    CONSTRAINT [PK_TB_PAGAMENTOS] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_PAGAMENTOS_TB_RESERVAS_ID_RESERVA] FOREIGN KEY ([ID_RESERVA]) REFERENCES [TB_RESERVAS] ([Id]) ON DELETE CASCADE
);
GO


CREATE TABLE [TB_VIAGANTES] (
    [Id] int NOT NULL IDENTITY,
    [NOME] nvarchar(max) NOT NULL,
    [DOCUMENTO] nvarchar(max) NOT NULL,
    [PASSAPORTE] nvarchar(max) NOT NULL,
    [ID_RESERVA] int NOT NULL,
    CONSTRAINT [PK_TB_VIAGANTES] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_TB_VIAGANTES_TB_RESERVAS_ID_RESERVA] FOREIGN KEY ([ID_RESERVA]) REFERENCES [TB_RESERVAS] ([Id]) ON DELETE CASCADE
);
GO


CREATE INDEX [IX_ImagensPacote_HistoricoPacoteId] ON [ImagensPacote] ([HistoricoPacoteId]);
GO


CREATE INDEX [IX_ImagensPacote_PacoteId] ON [ImagensPacote] ([PacoteId]);
GO


CREATE INDEX [IX_TB_AVALIACOES_ID_RESERVA] ON [TB_AVALIACOES] ([ID_RESERVA]);
GO


CREATE INDEX [IX_TB_CARTOES_USUARIO_ID] ON [TB_CARTOES] ([USUARIO_ID]);
GO


CREATE INDEX [IX_TB_DOCUMENTOS_USUARIO_ID] ON [TB_DOCUMENTOS] ([USUARIO_ID]);
GO


CREATE INDEX [IX_TB_ENDERECOS_USUARIO_ID] ON [TB_ENDERECOS] ([USUARIO_ID]);
GO


CREATE INDEX [IX_TB_MIDIAS_PACOTE_ID1] ON [TB_MIDIAS] ([PACOTE_ID1]);
GO


CREATE INDEX [IX_TB_PACOTES_PromocaoId] ON [TB_PACOTES] ([PromocaoId]);
GO


CREATE INDEX [IX_TB_PAGAMENTOS_ID_RESERVA] ON [TB_PAGAMENTOS] ([ID_RESERVA]);
GO


CREATE INDEX [IX_TB_RESERVAS_PACOTE_ID] ON [TB_RESERVAS] ([PACOTE_ID]);
GO


CREATE INDEX [IX_TB_RESERVAS_USUARIO_ID] ON [TB_RESERVAS] ([USUARIO_ID]);
GO


CREATE INDEX [IX_TB_USUARIOS_TIPO_USUARIO_ID] ON [TB_USUARIOS] ([TIPO_USUARIO_ID]);
GO


CREATE INDEX [IX_TB_VIAGANTES_ID_RESERVA] ON [TB_VIAGANTES] ([ID_RESERVA]);
GO


CREATE INDEX [IX_VideosPacote_HistoricoPacoteId] ON [VideosPacote] ([HistoricoPacoteId]);
GO


CREATE INDEX [IX_VideosPacote_PacoteId] ON [VideosPacote] ([PacoteId]);
GO


