INSERT INTO TB_TIPO_USUARIO (NOME) VALUES ('Cliente');
INSERT INTO TB_TIPO_USUARIO (NOME) VALUES ('Administrador');
INSERT INTO TB_TIPO_USUARIO (NOME) VALUES ('Funcionário');

INSERT INTO TB_USUARIOS (
    NOME,
    CPF,
    TELEFONE,
    DATA_NASCIMENTO,
    EMAIL,
    EMAIL_COMFIRMADO,
    TOKEN_EMAILCONFIRMADO,
    TOKEN_EXPIRACAO_EMAILCONFIRMADO,
    TOKEN_RECUPERACAO_SENHA,
    TOKEN_EXPIRACAO_RECUPERACAO_SENHA,
    SENHA,
    TIPO_USUARIO_ID
)
VALUES (
    'Administrador',
    '000.000.000-00',
    '(00) 00000-0000',
    '1990-01-01',
    'admin@decolatour.com',
    1,
    NULL,
    NULL,
    NULL,
    NULL,
    '$2b$12$D5ARIB.W7jXi5aOtGVSc8ecbLyv4ckX8/OhHx.JVWKVTMCZoAW0xm',
    1
);

INSERT INTO TB_USUARIOS (
    NOME,
    CPF,
    TELEFONE,
    DATA_NASCIMENTO,
    EMAIL,
    EMAIL_COMFIRMADO,
    TOKEN_EMAILCONFIRMADO,
    TOKEN_EXPIRACAO_EMAILCONFIRMADO,
    TOKEN_RECUPERACAO_SENHA,
    TOKEN_EXPIRACAO_RECUPERACAO_SENHA,
    SENHA,
    TIPO_USUARIO_ID
)
VALUES (
    'Pedro Guimarães',
    '110.000.000-01',
    '(00) 00000-0000',
    '1990-01-01',
    'pedro@decolatour.com',
    1,
    NULL,
    NULL,
    NULL,
    NULL,
    '$2b$12$rzXSc291A5pyvxg8E7wvWe9z2L0XLBxchx/BZz7JWTmKW9GUDVThC',
    1
);






